### ISSUE TITLE
XML Schedule Output Enhancements

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#13]
A couple of suggestions for the xml output for ease of use when parsing.

Make data-current a relative value so that the currently playing item is 0, the next item is 1 and the previous is -1 and sequentially in each direction. This will make it easier to parse both what's playing now and what's coming next, and leaves room to call and order the rest of the schedule.

Include a DateTime formatted data type entry for start time, (YYYY-MM-DDTHH:MM:SS, Example: 2017-07-29T09:30:00)

Include the server location and token as <server></server> and <token></token>

**Comment by justinemter** [comment]
> Make data-current a relative value so that the currently playing item is 0, the next item is 1 and the previous is -1 and sequentially in each direction. This will make it easier to parse both what's playing now and what's coming next, and leaves room to call and order the rest of the schedule.

This is interesting but if you are using python (or php) it should be trivial to determine the current, the previous and the future time entries by creating an array of XML time entries and just finding the "data-current" and minus 1 or + 1, etc. 

> Include a DateTime formatted data type entry for start time, (YYYY-MM-DDTHH:MM:SS, Example: 2017-07-29T09:30:00)

So since the schedules are being created on the fly every day for that day the year, month / day are irrelevant. The time object in python just defaults to 1900 (I could specify the real date but haven't yet needed to). I suppose this could be useful if I later added functionality to generate the schedule for the upcoming week, month or year... Anyway, you should be able to easily parse the time object using the python datetime object. Here's how I do it: 

`translated_time = datetime.datetime.strptime(timestr, '%I:%M %p').strftime('%Y-%m-%d %H:%M:%S')`

...the ''%Y-%m-%d %H:%M:%S" will translate the time in the XML output to your time. PHP has a similar method.
