### ISSUE TITLE
XML/HTML, multiple data-current=true values

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#18]
When two items are scheduled to play in the same minute, the xml and html schedules read both as "now playing."

Incredibly low priority, but I thought you may want to track on this in case it impacts something in the future,

**Comment by justinemter** [comment]
> When two items are scheduled to play in the same minute, the xml and html schedules read both as "now playing."

Hmm, I'm having difficulty picturing this situation. I definitely do not have error checking / adjusting if the user accidentally puts two `<time>` entries set to `strict-time` on the same day/time. Is this what you are referring to? Thanks for all this input

**Comment by MoeFwacky** [comment]
Sorry, I should have specified. This occurs when debug mode is on and the schedule/xml are also showing commercials, since commercials are typically under a minute long. Might not be worth fixing in the long run, but I thought i'd flag it anyway.

**Comment by justinemter** [comment]
Oh I see! Yeah, that's due to the html only refreshing every 30 seconds... doesn't clear the previously highlighted item in time. Rather than finding a better solution I'm going to wait for the webversion and update the html dynamically so it only refreshes when it needs to rather than every 30 seconds. It'll fix that bg image flash bug too.
