### ISSUE TITLE
Occasional 2-5 minute gap between last commercial and next scheduled media

### ISSUE THREAD

**Issue by MoeFwacky** [justinemter/pseudo-channel#35]
Commercials have been working great lately, but I've noticed a few recurring instances where the last commercial item will play, but leave a longer (sometimes as much as five minute) gap until the next scheduled show starts. 

The commercial gap was set to 25 seconds in the config. I set it for 10 seconds going forward with tomorrow's schedule just now when I updated to the latest develop branch version.

**Comment by justinemter** [comment]
> Commercials have been working great lately, but I've noticed a few recurring instances where the last commercial item will play, but leave a longer (sometimes as much as five minute) gap until the next scheduled show starts.

Hmm, I need to revisit this. It happens on my end where I have the config set to pad commercials with 5 minutes and get up to 1 or sometimes 2 minutes of extra gap before the last commercial and the next scheduled media. I suppose adding that extra "25" second padding will increase that significantly which is why you're experiencing such prolonged gaps.

**Comment by justinemter** [comment]
@MoeFwacky. I think I may make this my next problem to solve as it drives me nuts too. Just wanted to give you an update. Also, as a side note, I started a wiki in this repo. I've never done a github wiki. Right now it is editable by contributors so you should be able to edit/add pages if you wanted to. I found this great resource if you wanted to check it out: https://github.com/showcases/projects-with-great-wikis

Anyway, I am personally not used to wikis so need to study up.
