### ISSUE TITLE
Metadata usage

### ISSUE THREAD

**Issue by warrentc3** [justinemter/pseudo-channel#48]
@justinemter, didn't want to hijack the other issue any further.

hoping I can make some time to play around this weekend.  my thought was to leverage media metadata to help facilitate scheduling accuracy.  i use [plexpy](https://github.com/JonnyWong16/plexpy) for a multitude of things and it does a good job with the metadata.  I'd also like to attempt making a Plex "channel" to run the pseudo channels.

**Comment by justinemter** [comment]
hmm, I am curious how this would help with scheduling. I poked around with the above library a bit and it doesn't seem (to me) to have any features that would help with scheduling. I think when you get the app setup and start tinkering you'll get a better idea of how it works... it's one of those things where it clicks with you run it / stop it / configure it. 

> I'd also like to attempt making a Plex "channel" to run the pseudo channels.

Hmm, I don't know much about "Plex channels" but in theory, this is very very cool! I'd like to hear more...

**Comment by irodimus** [comment]
>I'd also like to attempt making a Plex "channel" to run the pseudo channels.

This is also something I'd like to see, if only because it would free up my RaspberryPi 3 as I already have Plex Media Server on my computer. I wouldn't also need another separate remote as I currently already use one for my HTPC setup. It also wouldn't need any resources as it would only run when selecting something to play.

Hopefully taking PseudoChannel's code and incorporating it into a Plex Channel is something that can be looked at sometime in the future, but for now, this project is certainly filling in that space nicely. I've spent most of my time using the RaspberryPi "changing channels" for movies and watching what's on for whatever lately instead of actually trying to find decide on what to watch. This 12 channels currently and I'm thinking of adding more.

Once a sort of tv block is added, I'll be set.

**Comment by justinemter** [comment]
Ahh, this is a very meta idea! I am going to close this as I really don't see this happening anytime soon.
